# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
#name: $(TeamProject)_$(Build.DefinitionName)_$(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  buildInfo: $(Build.ArtifactStagingDirectory)/info/'buildInfo.txt'
  myDate: $(Get-Date -Format yyyy.MMdd)

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- bash: |
    export var1=bob
    export var3=${var1}.isYourUncle
    echo "##vso[task.setvariable variable=var2;]$var3"
  displayName: 'set variable'

- script: |
    echo var2 is $(var2)

- bash: |
    mkdir $(Build.ArtifactStagingDirectory)/info
    echo Branch = $(Build.SourceBranch) >> $(buildInfo)
    echo Commit = $(Build.SourceVersion) >> $(buildInfo)
    echo Message = $(Build.SourceVersionMessage) >> $(buildInfo)
    cat $(buildInfo)
  displayName: 'create info file'

- bash: |
    value=$(<$(buildInfo))
    echo "##vso[task.setvariable variable=fileContents;]$value"
  displayName: 'slurp file contents into pipeline variable'

- bash: |
    echo $(fileContents)
  displayName: 'display variable from previous step'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/info'
    ArtifactName: 'info'
    publishLocation: 'Container'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/bin/Release'
    artifact: 'drop'
    publishLocation: 'pipeline'

#- task: PublishPipelineArtifact@1
#  inputs:
#    targetPath: '$(Build.SourcesDirectory)/bin/Release'
#    artifact: 'drop2'
#    publishLocation: 'pipeline'

#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#    ArtifactName: 'drop3'
#    publishLocation: 'Container'